#pragma once
#define BUILD  0  // 5 == BUILD_TRACE
#define OPENMP 1
#define CUDA   1
#include "_main.hxx"
#include "Graph.hxx"
#include "vertices.hxx"
#include "edges.hxx"
#include "csr.hxx"
#include "csr_old.hxx"
#include "snap.hxx"
#include "mtx.hxx"
#include "duplicate.hxx"
#include "transpose.hxx"
#include "deadEnds.hxx"
#include "selfLoop.hxx"
#include "components.hxx"
#include "sort.hxx"
#include "identicals.hxx"
#include "dynamic.hxx"
#include "pagerank.hxx"
#include "pagerankSeq.hxx"
#include "pagerankOmp.hxx"
#include "pagerankCuda.hxx"
// #include "pagerankNvgraph.hxx"
#include "pagerankMonolithicSeq.hxx"
#include "pagerankMonolithicOmp.hxx"
#include "pagerankMonolithicCuda.hxx"
#include "pagerankComponentwiseSeq.hxx"
#include "pagerankComponentwiseOmp.hxx"
#include "pagerankComponentwiseCuda.hxx"
#include "pagerankLevelwiseSeq.hxx"
#include "pagerankLevelwiseOmp.hxx"
#include "pagerankLevelwiseCuda.hxx"
